<a href="https://colab.research.google.com/github/Aarif-Mir/Pytorch/blob/main/1Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():              # runtime --> change runtime type --> hardware accelerator
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


Creating a Tensor

In [ ]:
#using empty
a = torch.empty(2,3)

In [ ]:
#check type
type(a)

torch.Tensor

In [ ]:
a

tensor([[1.5030e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(4,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
torch.rand(2,3)     # value 0 to 1   each time different output

tensor([[0.0020, 0.5437, 0.8479],
        [0.9898, 0.6845, 0.4194]])

In [ ]:
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [ ]:
# manual_seed
torch.manual_seed(100)      # to get the same random values every time keeping seed same
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)      # reproducibility
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor        --> values u want
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2)) # start end step

# using linspace      # (start) (end) (no. of numbers which are evenlyspaced )
print("using linspace ->", torch.linspace(0,10,10))

# using eye            # identity matrix
print("using eye ->", torch.eye(5))

# using full           # shape and element
print("using full ->", torch.full((3, 3), 5))   # shape is 3*3 and the element is 5 only at each place

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


**Tensor Shapes**

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
print(x.shape)

torch.Size([2, 3])


In [ ]:
#creating tensors of same shape
torch.empty_like(x)

tensor([[3616445622929465956, 6068934943515422005, 3977868379665610288],
        [6499311316895150126, 7309453675965983778, 8315168162784306286]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x)   #error x kai sarai numbers integers hai aur rand float type numbers generate krta hai

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [ ]:
torch.rand_like(x, dtype=torch.float32) # solution --> change the datatype


tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

### **Tensor Data types**


In [ ]:
#Find datatype
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0] , dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:

torch.tensor([1,2,3] , dtype=torch.float32)


tensor([1., 2., 3.])

In [ ]:
# using to()  --> change datatype
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [ ]:
#ELEMENT WISE OPERATIONS
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])

### 2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2094, 0.1071, 0.4068],
        [0.7041, 0.4229, 0.1070]])
tensor([[0.2928, 0.1881, 0.7012],
        [0.3024, 0.4475, 0.7767]])


In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.2094, 0.1071, 0.4068],
        [0.0992, 0.4229, 0.1070]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
c.dtype

torch.int64

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[2, 6, 7],
        [7, 8, 3]])

In [ ]:
f = torch.randint(size=(2,3),high=50) # irrespective of size one more arg is must to enter
f

tensor([[36, 41, 25],
        [15, 10,  4]])

In [ ]:
# sum
torch.sum(e)
# sum along columns
print("sum along col :", torch.sum(e, dim=0))
# sum along rows
print("sum along row :", torch.sum(e, dim=1))

sum along col : tensor([ 9, 14, 10])
sum along row : tensor([15, 18])


In [ ]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

In [ ]:
e

tensor([[3., 8., 8.],
        [3., 3., 5.]])

In [ ]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([3.0000, 5.5000, 6.5000])

In [ ]:
# median
torch.median(e)

tensor(3.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(3.)

In [ ]:
# product
torch.prod(e)

tensor(8640.)

In [ ]:
# standard deviation
torch.std(e)

tensor(2.4495)

In [ ]:
# variance
torch.var(e)

tensor(6.)

In [ ]:
# argmax
torch.argmax(e)

tensor(1)

In [ ]:
# argmin
torch.argmin(e)

tensor(0)

### 4. Matrix operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[0, 6, 4],
        [0, 8, 4]])
tensor([[7, 2],
        [3, 8],
        [5, 6]])


In [ ]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[38, 72],
        [44, 88]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product      # on vectors not matricies --> for matricies --> torch.matmul()
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
f

tensor([[0, 6, 4],
        [0, 8, 4]])

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[0, 0],
        [6, 8],
        [4, 4]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[2., 9., 5.],
        [0., 4., 2.],
        [7., 1., 1.]])

In [ ]:
# determinant
torch.det(h)

tensor(-10.0000)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.2000,  0.4000,  0.2000],
        [-1.4000,  3.3000,  0.4000],
        [ 2.8000, -6.1000, -0.8000]])

### 5. Comparison operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[5, 4, 4],
        [1, 1, 2]])
tensor([[4, 7, 2],
        [5, 6, 1]])


In [ ]:
# greater than
i > j               # boolean matrix
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i>= j
# less than equal to

tensor([[ True, False,  True],
        [False, False,  True]])

### 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[4., 5., 6.],
        [9., 2., 3.]])

In [ ]:
# log
torch.log(k)

tensor([[1.3863, 1.6094, 1.7918],
        [2.1972, 0.6931, 1.0986]])

In [ ]:
# exp
torch.exp(k)

tensor([[5.4598e+01, 1.4841e+02, 4.0343e+02],
        [8.1031e+03, 7.3891e+00, 2.0086e+01]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[2.0000, 2.2361, 2.4495],
        [3.0000, 1.4142, 1.7321]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9820, 0.9933, 0.9975],
        [0.9999, 0.8808, 0.9526]])

In [ ]:
# softmax
torch.softmax(k, dim=0)                # datatype must be float

tensor([[0.0067, 0.9526, 0.9526],
        [0.9933, 0.0474, 0.0474]])

In [ ]:
# relu
torch.relu(k)

tensor([[4., 5., 6.],
        [9., 2., 3.]])

## Inplace Operations
_ for inplace operation

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])
tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])


In [ ]:
m.add_(n)   # result stored back in m

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

In [ ]:
m

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

In [ ]:
n

tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])

In [ ]:
torch.add(m, n)

tensor([[2.4817, 1.0582, 2.3761],
        [1.3696, 1.2339, 1.4910]])

In [ ]:
m

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

In [ ]:
torch.add_(m,n)

AttributeError: module 'torch' has no attribute 'add_'

In [ ]:
torch.relu(m)

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

In [ ]:
m.relu_()

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

In [ ]:
m

tensor([[1.5705, 0.5734, 1.4325],
        [0.9792, 0.9839, 1.1703]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.9753, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.9753, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [ ]:
b    # change in b also

tensor([[0.0000, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

In [ ]:
id(a)

138333720292208

In [ ]:
id(b)

138333720292208

In [ ]:
b = a.clone()

In [ ]:

a[0][0] = 999

In [ ]:
a

tensor([[9.9900e+02, 7.5818e-01, 6.6880e-01],
        [2.6512e-01, 2.3362e-01, 5.0568e-01]])

In [ ]:
b

tensor([[0.0000, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])

# Tensor operations on GPU

In [ ]:
torch.cuda.is_available()

False

In [ ]:
device = torch.device("cuda")

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
device

device(type='cpu')

In [ ]:
#creating a tensor on Gpu
torch.rand((2,3), device=device)

tensor([[0.0677, 0.0560, 0.4322],
        [0.3404, 0.5005, 0.0596]], device='cuda:0')

In [ ]:
#Moving an existing tensor to GPU
a = torch.rand((2,3))
a

tensor([[0.5688, 0.0634, 0.8993],
        [0.2732, 0.3397, 0.1879]])

In [ ]:
b = a.to(device)

In [ ]:
b + 5

tensor([[5.5688, 5.0634, 5.8993],
        [5.2732, 5.3397, 5.1879]])

In [ ]:
# comparison

# Reshaping Tensors


In [ ]:
a = torch.ones(2,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#reshape
a.reshape(4,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
a.reshape(2,2,2)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [ ]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)         #  2 matrices each of shape (3, 4)
b

tensor([[[0.5534, 0.2682, 0.9556, 0.9761],
         [0.5934, 0.3124, 0.9431, 0.8519],
         [0.9815, 0.1132, 0.4783, 0.4436]],

        [[0.3847, 0.4521, 0.5569, 0.9952],
         [0.0015, 0.0813, 0.4907, 0.2130],
         [0.4603, 0.1386, 0.0277, 0.5662]]])

In [ ]:
#permute
b.permute(2,0,1)

tensor([[[0.5534, 0.5934, 0.9815],
         [0.3847, 0.0015, 0.4603]],

        [[0.2682, 0.3124, 0.1132],
         [0.4521, 0.0813, 0.1386]],

        [[0.9556, 0.9431, 0.4783],
         [0.5569, 0.4907, 0.0277]],

        [[0.9761, 0.8519, 0.4436],
         [0.9952, 0.2130, 0.5662]]])

In [ ]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
#unsqeeze  --> Adds a dimension of size 1 at the specified position.
c = torch.rand(226,226,3)
c.shape

torch.Size([226, 226, 3])

In [ ]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [ ]:
#sqeeze   -->  Removes dimensions of size 1 (singleton dimensions) from a tensor's shape.
d = torch.rand(1,20,6)    # ist argument Usually the batch size (number of samples processed together) and the rest is the shape
d.shape

torch.Size([1, 20, 6])

In [ ]:
torch.rand(2,3)

tensor([[0.3438, 0.3719, 0.3974],
        [0.4867, 0.9536, 0.2706]])

In [ ]:
torch.randint(high=10, size=(2,3))

tensor([[2, 0, 1],
        [5, 0, 1]])

In [ ]:
d.squeeze(0).shape

torch.Size([20, 6])

# Numpy and Pytorch

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()
b

array([1, 2, 3])

In [ ]:
import numpy as np

In [ ]:
c = np.array([1,2,3,4])

In [ ]:
d = torch.from_numpy(c)
d

tensor([1, 2, 3, 4])

# New Section

In [ ]:
import numpy as np

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y = np.array([[7,8,9],[4,5,6],[1,2,3]])
y


array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
np.multiply(x,y)

array([[ 7, 16, 27],
       [16, 25, 36],
       [ 7, 16, 27]])

In [ ]:
2 * x

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
x * y

array([[ 7, 16, 27],
       [16, 25, 36],
       [ 7, 16, 27]])