<a href="https://colab.research.google.com/github/Aarif-Mir/Pytorch/blob/main/4pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#optimizing previous file
# 1 Building the Neural Network using nn Module
# 2 Using built-in activation function
# 3 Using built-in loss function
# 4 using built-in optimizer

In [ ]:
#Creating model class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
        super(Model, self).__init__()
        self.linear = nn.Linear(num_features, 1)        # layer --> i/p = num_features(number of inputs or features) , 1 o/p
        self.sigmoid = nn.Sigmoid()


    def forward(self, features):
        out = self.linear(features)          # calculating w * x + b
        out = self.sigmoid(out)
        return out




In [ ]:
# Create dataset
features = torch.rand(10,5)

#Create Model
model = Model(features.shape[1])

# Call model for the forward pass
# model.forward(features)                                                       # wil work but not recommended
model(features)                                                                 # pytorch has over written the __call__ magic method so we can can like this

tensor([[0.5241],
        [0.4922],
        [0.5413],
        [0.5624],
        [0.5137],
        [0.4572],
        [0.4913],
        [0.5112],
        [0.5082],
        [0.5315]], grad_fn=<SigmoidBackward0>)

In [ ]:
#show model weights
model.linear.weight

Parameter containing:
tensor([[0.1477, 0.1554, 0.2300, 0.0434, 0.1585]], requires_grad=True)

In [ ]:
# bias
model.linear.bias

Parameter containing:
tensor([-0.3309], requires_grad=True)

In [ ]:
# for visualization  we use torchinfo
!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model, input_size = (10,5) )

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# **Hidden Layer with multiple neurons**

In [ ]:
#Creating model class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
        super(Model, self).__init__()
        self.linear1 = nn.Linear(num_features, 3)        # layer --> i/p = num_features(number of inputs or features) , 3 o/p
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)        # layer --> i/p = num_features(number of inputs from previous layer) , 1 o/p
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear1(features)          # calculating w * x + b
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out




In [ ]:
# Create dataset
features = torch.rand(10,5)

#Create Model
model = Model(features.shape[1])

# Call model for the forward pass
model(features)

tensor([[0.6373],
        [0.6291],
        [0.6242],
        [0.6084],
        [0.6245],
        [0.6406],
        [0.6121],
        [0.6682],
        [0.6183],
        [0.6740]], grad_fn=<SigmoidBackward0>)

In [ ]:
#show model weights
model.linear1.weight

Parameter containing:
tensor([[-0.2174,  0.0644,  0.2188,  0.3159,  0.1977],
        [-0.2158,  0.1516,  0.1749, -0.0779,  0.1810],
        [-0.3860, -0.3777,  0.0958, -0.4226,  0.2403]], requires_grad=True)

In [ ]:
model.linear1.weight.shape

torch.Size([3, 5])

In [ ]:
from torchinfo import summary
summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# **What is nn.Sequential?**
- nn.Sequential is a container module. It allows you to stack multiple layers/modules together in the order you want them to be applied.




In [ ]:
#Creating model class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
        super(Model, self).__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
      out = self.network(features)
      return out


In [ ]:
# Create dataset
features = torch.rand(10,5)

#Create Model
model = Model(features.shape[1])

# Call model for the forward pass
model(features)

tensor([[0.4497],
        [0.4595],
        [0.4454],
        [0.4474],
        [0.4545],
        [0.4496],
        [0.4413],
        [0.4520],
        [0.4459],
        [0.4604]], grad_fn=<SigmoidBackward0>)

In [ ]:
summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

from collections import OrderedDict
# You can also give names to layers using OrderedDict:
- model = nn.Sequential(OrderedDict([
- -    ('fc1', nn.Linear(10, 50)),
- -    ('relu', nn.ReLU()),
- -    ('fc2', nn.Linear(50, 1))
- - ]))

This helps when you want to access specific layers by name:

- print(model['fc1'])      # prints the first Linear layer

# **Optimizing previous code file 3pytorch-training-pipeline**

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [ ]:
X_train.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
273        9.742         15.67           61.50      289.9          0.09037   
531       11.670         20.02           75.21      416.2          0.10160   
420       11.570         19.04           74.20      409.7          0.08546   
362       12.760         18.84           81.87      496.6          0.09676   
206        9.876         17.27           62.92      295.4          0.10890   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
273           0.04689         0.01103              0.01407         0.2081   
531           0.09453         0.04200              0.02157         0.1859   
420           0.07722         0.05485              0.01428         0.2031   
362           0.07952         0.02688              0.01781         0.1759   
206           0.07232         0.01756              0.01952         0.1934   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
273                 0.06312  ...         10.75          20.88   
531                 0.06461  ...         13.35          28.81   
420                 0.06267  ...         13.07          26.98   
362                 0.06183  ...         13.75          25.99   
206                 0.06285  ...         10.42          23.22   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
273            68.09       355.2            0.1467             0.0937   
531            87.00       550.6            0.1550             0.2964   
420            86.43       520.5            0.1249             0.1937   
362            87.82       579.7            0.1298             0.1839   
206            67.08       331.6            0.1415             0.1247   

     concavity_worst  concave points_worst  symmetry_worst  \
273          0.04043               0.05159          0.2841   
531          0.27580               0.08120          0.3206   
420          0.25600               0.06664          0.3035   
362          0.12550               0.08312          0.2744   
206          0.06213               0.05588          0.2989   

     fractal_dimension_worst  
273                  0.08175  
531                  0.08950  
420                  0.08284  
362                  0.07238  
206                  0.07380  

[5 rows x 30 columns]

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-1.24672426, -0.82635587, -1.25667944, ..., -0.96917569,
        -0.12361326, -0.12734586],
       [-0.69794999,  0.21252015, -0.68991757, ..., -0.5159587 ,
         0.44474421,  0.31536346],
       [-0.72641338, -0.02152548, -0.73167027, ..., -0.73881718,
         0.17847263, -0.06508094],
       ...,
       [ 0.23564939, -0.37259393,  0.20466499, ...,  0.79272256,
         0.76863011, -0.71457836],
       [-0.31654049,  0.73792871, -0.40881029, ..., -1.61710302,
        -0.97381374, -1.45947251],
       [ 1.3941096 ,  1.30393703,  1.24434852, ...,  1.23507214,
         1.61260202,  0.50844185]])

In [ ]:
y_train.head()

273    B
531    B
420    B
362    B
206    B
Name: diagnosis, dtype: object

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0])

In [ ]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))    # Make sure X_train_tensor and y_train_tensor are converted to float32. else RuntimeError: mat1 and mat2 must have the same dtype, but got Double and Float

X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  # def __init__(self, num_features):
  #   super(MySimpleNN,self).__init__()
  #   self.network =nn.Sequential(
  #       nn.linear(num_features, 1),
  #       nn.Sigmoid()

  #   )

  # def forward(self, features):
  #   y_pred = self.network(features)
  #   return y_pred

  def __init__(self, num_features):
    super(MySimpleNN, self).__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    y_pred = self.sigmoid(out)
    return y_pred



  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.721220850944519
Epoch: 2, Loss: 0.7163408994674683
Epoch: 3, Loss: 0.712132453918457
Epoch: 4, Loss: 0.7084415555000305
Epoch: 5, Loss: 0.7051645517349243
Epoch: 6, Loss: 0.702227771282196
Epoch: 7, Loss: 0.6995764970779419
Epoch: 8, Loss: 0.6971680521965027
Epoch: 9, Loss: 0.6949688792228699
Epoch: 10, Loss: 0.692951500415802
Epoch: 11, Loss: 0.6910939812660217
Epoch: 12, Loss: 0.6893776655197144
Epoch: 13, Loss: 0.6877871155738831
Epoch: 14, Loss: 0.6863092184066772
Epoch: 15, Loss: 0.684933066368103
Epoch: 16, Loss: 0.6836490631103516
Epoch: 17, Loss: 0.6824489831924438
Epoch: 18, Loss: 0.6813254952430725
Epoch: 19, Loss: 0.6802722811698914
Epoch: 20, Loss: 0.6792839169502258
Epoch: 21, Loss: 0.6783552169799805
Epoch: 22, Loss: 0.6774815917015076
Epoch: 23, Loss: 0.6766592264175415
Epoch: 24, Loss: 0.6758845448493958
Epoch: 25, Loss: 0.6751540899276733


In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6315789222717285


In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.1061,  0.0198, -0.0336,  0.1388, -0.0067, -0.1439, -0.1043, -0.0937,
          0.0133,  0.1349,  0.0408,  0.0671, -0.0413,  0.0612, -0.0400,  0.1245,
         -0.0056, -0.0948, -0.0813, -0.0251, -0.0869, -0.0708,  0.1104, -0.1573,
         -0.0834,  0.1077,  0.0581,  0.0941,  0.0921, -0.0450]],
       requires_grad=True)

# **Loss and optimizer**


In [ ]:
import torch.nn as nn

class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super(MySimpleNN, self).__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    y_pred = self.sigmoid(out)
    return y_pred


In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
y_train_tensor.shape

torch.Size([455, 1])

In [ ]:
# y_train_tensor

In [ ]:
# y_train_tensor.unsqueeze_(1).shape   # either this

torch.Size([455, 1])

In [ ]:
#define Loss Function
loss_function = nn.BCELoss()

In [ ]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

#define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  # loss = loss_function(y_pred, y_train_tensor)
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))    #or this  # # view(-1, 1) reshapes labels from [batch_size] to [batch_size, 1]
# -1 lets PyTorch infer the correct number of rows automatically

  # clear gradients              # best to first clear the gradients and then calculate the new ones
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # # zero gradients
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.736291766166687
Epoch: 2, Loss: 0.5367220640182495
Epoch: 3, Loss: 0.43812859058380127
Epoch: 4, Loss: 0.3803251385688782
Epoch: 5, Loss: 0.34173065423965454
Epoch: 6, Loss: 0.3137611150741577
Epoch: 7, Loss: 0.29233548045158386
Epoch: 8, Loss: 0.27525588870048523
Epoch: 9, Loss: 0.2612285017967224
Epoch: 10, Loss: 0.24943892657756805
Epoch: 11, Loss: 0.23934710025787354
Epoch: 12, Loss: 0.23057949542999268
Epoch: 13, Loss: 0.22286872565746307
Epoch: 14, Loss: 0.21601778268814087
Epoch: 15, Loss: 0.20987780392169952
Epoch: 16, Loss: 0.20433400571346283
Epoch: 17, Loss: 0.19929620623588562
Epoch: 18, Loss: 0.19469238817691803
Epoch: 19, Loss: 0.19046427309513092
Epoch: 20, Loss: 0.18656402826309204
Epoch: 21, Loss: 0.18295204639434814
Epoch: 22, Loss: 0.17959506809711456
Epoch: 23, Loss: 0.17646507918834686
Epoch: 24, Loss: 0.17353811860084534
Epoch: 25, Loss: 0.17079371213912964


In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5346260666847229
